
#include "config.h"
#ifndef DEV_TIMER_DECODER_CFG_H
#define DEV_TIMER_DECODER_CFG_H
#if CONFIG_TIMER_DECODER_EN
#ifndef CONFIG_TIMER_DECODER_CHANNEL_MAX
#error "CONFIG_TIMER_DECODER_CHANNEL_MAX is not defined"
#define CONFIG_TIMER_DECODER_CHANNEL_MAX CONFIG_TIMER_DECODER_CHANNEL_MAX
#endif

// Parameters
#define DEFAULT_TIMER_VALUE (0xFFFFFFFF / 2)

#if CONFIG_TIMER_DECODER_CHANNEL_MAX > 1
#define TIMER_DECODER_CH0_EN 1
#define TIMER_DECODER_CH1_EN 1
#elif CONFIG_TIMER_DECODER_CHANNEL_MAX > 0
#define TIMER_DECODER_CH0_EN 1
#define TIMER_DECODER_CH1_EN 0
#else
#define TIMER_DECODER_CH0_EN 0
#define TIMER_DECODER_CH1_EN 0
#endif  // CONFIG_TIMER_DECODER_CHANNEL_MAX > 1

/* Chanel0 */
#if TIMER_DECODER_CH0_EN
// RCU  CONFIG_ENCODER_CH0_TIMER_RCU
// GPIO
#if (CONFIG_ENCODER_CH0_TIMER == TIMER22)
#define ENCODER_CH0_TIMER_RCU  CONFIG_ENCODER_CH0_TIMER_RCU
#define ENCODER_CH0_TIMER      CONFIG_ENCODER_CH0_TIMER
#define ENCODER_CH0_GPIO_RCU   RCU_GPIOG
#define ENCODER_CH0_GPIO_PORT  GPIOG
#define ENCODER_CH0_GPIO_AF    GPIO_AF_13
#define ENCODER_CH0_GPIO_PIN_A GPIO_PIN_12
#define ENCODER_CH0_GPIO_PIN_B GPIO_PIN_13
#else
#error "CONFIG_ENCODER_CH0_TIMER is not defined or invalid"

#endif  // CONFIG_ENCODER_CH0_TIMER

#endif  // TIMER_DECODER_CH0_EN

/* Channel1 */
#if TIMER_DECODER_CH1_EN
// RCU  CONFIG_ENCODER_CH1_TIMER_RCU
// GPIO
#if (CONFIG_ENCODER_CH1_TIMER == TIMER2)
#define ENCODER_CH1_TIMER_RCU  CONFIG_ENCODER_CH1_TIMER_RCU
#define ENCODER_CH1_TIMER      CONFIG_ENCODER_CH1_TIMER
#define ENCODER_CH1_GPIO_RCU   RCU_GPIOB
#define ENCODER_CH1_GPIO_PORT  GPIOB
#define ENCODER_CH1_GPIO_AF    GPIO_AF_2
#define ENCODER_CH1_GPIO_PIN_A GPIO_PIN_4
#define ENCODER_CH1_GPIO_PIN_B GPIO_PIN_5
#else
#error "CONFIG_ENCODER_CH1_TIMER is not defined or invalid"

#endif  // CONFIG_ENCODER_CH0_TIMER

#endif

#define CONFIG_ENCODER_CYCLE_TIMER_MS 100
// 0~40mv
#define MAX_PHY_VALUE_CH0  (0.04f)  // V
#define DEF_PHY_VALUE_CH0  (0.02f)  // 默认物理值
#define MIN_PHY_VALUE_CH0  (-0.004f)
#define STEP_PHY_VALUE_CH0 (10.0 / 1000.0 / 1000.0f)  // 每步物理值10uv

#define MAX_PHY_VALUE_CH1  (9.0f)  // V
#define DEF_PHY_VALUE_CH1  (4.5f)  // 默认物理值
#define MIN_PHY_VALUE_CH1  (0.0f)
#define STEP_PHY_VALUE_CH1 (5.0 / 1000.0f)  // 每步物理值

/*
pluse_gain
*/
#define CONFIG_ENCODER_PULSE_GAIN_DEFAULT    1
#define CONFIG_ENCODER_DURATION_GAIN_DEFAULT 1
#ifndef CONFIG_ENCODER_ONE_PULSE_CNT
/* 触发一次转转产生的计时器变化的数值 */
#define CONFIG_ENCODER_ONE_PULSE_CNT 4
/* 消抖时间 */
#define CONFIG_ENCODER_DEBOUNCE_TIME_MS 100
/* 有效超时时间 */
#define CONFIG_ENCODER_ACTIVE_TIMEOUT_MS 1000  // 3秒
#define CONFIG_ENCODER_CH0_TIMER_MS      100
#endif  // CONFIG_ENCODER_ONE_PULSE_CNT

#endif  // DEV_TIMER_DECODER_CFG_H

#endif  // CONFIG_TIMER_DECODER_EN
