#ifndef __DEV_UART_CFG_H__
#define __DEV_UART_CFG_H__
#include "device_config.h"

/* DEFINE */

#define DEV_UART0_ENABLE (1)   // DEVICE_UART0_ENABLE
#define DEV_UART0_BAUND 115200 //   DEVICE_UART0_BAUND
#define DEV_UART0_RX_BUFFER_SIZE (128)
#define DEV_UART0_TX_BUFFER_SIZE (128)
/* DMA */
#define DEV_UART0_RX_DMA_ENABLE (0)
#define DEV_UART0_DMA_RX_BASE DMA0
#define DEV_UART0_DMA_RX_CHANNEL DMA_CH1
#define DEV_UART0_DMA_RX_REQUEST DMA_REQUEST_USART0_RX
#define DEV_UART0_RX_DMA_PRIORITY DMA_PRIORITY_HIGH
#define DEV_UART0_TX_DMA_ENABLE (1)
#define DEV_UART0_DMA_TX_BASE DMA0
#define DEV_UART0_DMA_TX_CHANNEL DMA_CH0
#define DEV_UART0_DMA_TX_REQUEST DMA_REQUEST_USART0_TX
#define DEV_UART0_TX_DMA_PRIORITY DMA_PRIORITY_HIGH

/* GPIO */
#define DEV_UART0_GPIO_PORT GPIOB
#define DEV_UART0_GPIO_CLK (RCU_GPIOB)
#define DEV_UART0_AF GPIO_AF_7
#define DEV_UART0_TX_PIN GPIO_PIN_6
#define DEV_UART0_RX_PIN GPIO_PIN_7
#define DEV_UART0_CLK (RCU_USART0)
/* DMA */

// #define DEV_UART1_ENABLE DEVICE_UART1_ENABLE
// #define DEV_UART1_BAUND DEVICE_UART1_BAUND
// #define DEV_UART2_ENABLE DEVICE_UART2_ENABLE
// #define DEV_UART2_BAUND DEVICE_UART2_BAUND
// #define DEV_UART3_ENABLE DEVICE_UART3_ENABLE
// #define DEV_UART3_BAUND DEVICE_UART3_BAUND
// #define DEV_UART4_ENABLE DEVICE_UART4_ENABLE
// #define DEV_UART4_BAUND DEVICE_UART4_BAUND
// #define DEV_UART5_ENABLE DEVICE_UART5_ENABLE
// #define DEV_UART5_BAUND DEVICE_UART5_BAUND
// #define DEV_UART6_ENABLE DEVICE_UART6_ENABLE
// #define DEV_UART6_BAUND DEVICE_UART6_BAUND
// #define DEV_UART7_ENABLE DEVICE_UART7_ENABLE
// #define DEV_UART7_BAUND DEVICE_UART7_BAUND

#endif // __DEV_UART_CFG_H__