
#include "config.h"
#ifndef DEV_TIMER_DECODER_CFG_H
#define DEV_TIMER_DECODER_CFG_H
#if CONFIG_TIMER_DECODER_EN
#define TIMER_DECODER_EN 1

// CONFIG_ENCODER_CH0_TIMER
#define ENCODER_CH0_TIMER TIMER22

#define ENCODER_TIMER_RCU RCU_TIMER22
#define ENCODER_TIMER TIMER22

#define TIMER_A_CH_RCU RCU_GPIOG
#define TIMER_B_CH_RCU RCU_GPIOG
#define TIMER_A_CH_PORT GPIOG
#define TIMER_B_CH_PORT GPIOG
#define TIMER_A_CH_PIN GPIO_PIN_12
#define TIMER_B_CH_PIN GPIO_PIN_13

#define DEFAULT_TIMER_VALUE (0xFFFFFFFF / 2)

#define TIMER_A_CH_AF GPIO_AF_2
#define TIMER_B_CH_AF GPIO_AF_2

#else
#define TIMER_DECODER_EN 0
#endif

#endif // DEV_TIMER_DECODER_CFG_H
